// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: youme_userinfo.proto

#ifndef PROTOBUF_youme_5fuserinfo_2eproto__INCLUDED
#define PROTOBUF_youme_5fuserinfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace YOUMEServiceProtocol {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_youme_5fuserinfo_2eproto();
void protobuf_AssignDesc_youme_5fuserinfo_2eproto();
void protobuf_ShutdownFile_youme_5fuserinfo_2eproto();

class GetUserInfoReq;
class GetUserInfoRsp;
class UpdateUserInfoReq;
class UpdateUserInfoRsp;

// ===================================================================

class GetUserInfoReq : public ::youmecommon::protobuf::MessageLite {
 public:
  GetUserInfoReq();
  virtual ~GetUserInfoReq();

  GetUserInfoReq(const GetUserInfoReq& from);

  inline GetUserInfoReq& operator=(const GetUserInfoReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const GetUserInfoReq& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GetUserInfoReq* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GetUserInfoReq* other);

  // implements Message ----------------------------------------------

  inline GetUserInfoReq* New() const { return New(NULL); }

  GetUserInfoReq* New(::youmecommon::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::youmecommon::protobuf::MessageLite& from);
  void CopyFrom(const GetUserInfoReq& from);
  void MergeFrom(const GetUserInfoReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::youmecommon::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::youmecommon::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetUserInfoReq* other);
  private:
  inline ::youmecommon::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::youmecommon::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::youmecommon::protobuf::int32 version() const;
  void set_version(::youmecommon::protobuf::int32 value);

  // required bytes user_id = 2;
  bool has_user_id() const;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  void set_user_id(const char* value);
  void set_user_id(const void* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetUserInfoReq)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_user_id();
  inline void clear_has_user_id();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::youmecommon::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::youmecommon::protobuf::Arena* _arena_ptr_;

  ::youmecommon::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::youmecommon::protobuf::internal::ArenaStringPtr user_id_;
  ::youmecommon::protobuf::int32 version_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto();
  #endif
  friend void protobuf_AssignDesc_youme_5fuserinfo_2eproto();
  friend void protobuf_ShutdownFile_youme_5fuserinfo_2eproto();

  void InitAsDefaultInstance();
  static GetUserInfoReq* default_instance_;
};
// -------------------------------------------------------------------

class GetUserInfoRsp : public ::youmecommon::protobuf::MessageLite {
 public:
  GetUserInfoRsp();
  virtual ~GetUserInfoRsp();

  GetUserInfoRsp(const GetUserInfoRsp& from);

  inline GetUserInfoRsp& operator=(const GetUserInfoRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const GetUserInfoRsp& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GetUserInfoRsp* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GetUserInfoRsp* other);

  // implements Message ----------------------------------------------

  inline GetUserInfoRsp* New() const { return New(NULL); }

  GetUserInfoRsp* New(::youmecommon::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::youmecommon::protobuf::MessageLite& from);
  void CopyFrom(const GetUserInfoRsp& from);
  void MergeFrom(const GetUserInfoRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::youmecommon::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::youmecommon::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetUserInfoRsp* other);
  private:
  inline ::youmecommon::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::youmecommon::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::youmecommon::protobuf::int32 version() const;
  void set_version(::youmecommon::protobuf::int32 value);

  // required bytes user_info = 2;
  bool has_user_info() const;
  void clear_user_info();
  static const int kUserInfoFieldNumber = 2;
  const ::std::string& user_info() const;
  void set_user_info(const ::std::string& value);
  void set_user_info(const char* value);
  void set_user_info(const void* value, size_t size);
  ::std::string* mutable_user_info();
  ::std::string* release_user_info();
  void set_allocated_user_info(::std::string* user_info);

  // optional double longitude = 3;
  bool has_longitude() const;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 3;
  double longitude() const;
  void set_longitude(double value);

  // optional double latitude = 4;
  bool has_latitude() const;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 4;
  double latitude() const;
  void set_latitude(double value);

  // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetUserInfoRsp)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_user_info();
  inline void clear_has_user_info();
  inline void set_has_longitude();
  inline void clear_has_longitude();
  inline void set_has_latitude();
  inline void clear_has_latitude();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::youmecommon::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::youmecommon::protobuf::Arena* _arena_ptr_;

  ::youmecommon::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::youmecommon::protobuf::internal::ArenaStringPtr user_info_;
  double longitude_;
  double latitude_;
  ::youmecommon::protobuf::int32 version_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto();
  #endif
  friend void protobuf_AssignDesc_youme_5fuserinfo_2eproto();
  friend void protobuf_ShutdownFile_youme_5fuserinfo_2eproto();

  void InitAsDefaultInstance();
  static GetUserInfoRsp* default_instance_;
};
// -------------------------------------------------------------------

class UpdateUserInfoReq : public ::youmecommon::protobuf::MessageLite {
 public:
  UpdateUserInfoReq();
  virtual ~UpdateUserInfoReq();

  UpdateUserInfoReq(const UpdateUserInfoReq& from);

  inline UpdateUserInfoReq& operator=(const UpdateUserInfoReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const UpdateUserInfoReq& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const UpdateUserInfoReq* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(UpdateUserInfoReq* other);

  // implements Message ----------------------------------------------

  inline UpdateUserInfoReq* New() const { return New(NULL); }

  UpdateUserInfoReq* New(::youmecommon::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::youmecommon::protobuf::MessageLite& from);
  void CopyFrom(const UpdateUserInfoReq& from);
  void MergeFrom(const UpdateUserInfoReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::youmecommon::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::youmecommon::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateUserInfoReq* other);
  private:
  inline ::youmecommon::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::youmecommon::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::youmecommon::protobuf::int32 version() const;
  void set_version(::youmecommon::protobuf::int32 value);

  // required bytes user_info = 2;
  bool has_user_info() const;
  void clear_user_info();
  static const int kUserInfoFieldNumber = 2;
  const ::std::string& user_info() const;
  void set_user_info(const ::std::string& value);
  void set_user_info(const char* value);
  void set_user_info(const void* value, size_t size);
  ::std::string* mutable_user_info();
  ::std::string* release_user_info();
  void set_allocated_user_info(::std::string* user_info);

  // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.UpdateUserInfoReq)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_user_info();
  inline void clear_has_user_info();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::youmecommon::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::youmecommon::protobuf::Arena* _arena_ptr_;

  ::youmecommon::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::youmecommon::protobuf::internal::ArenaStringPtr user_info_;
  ::youmecommon::protobuf::int32 version_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto();
  #endif
  friend void protobuf_AssignDesc_youme_5fuserinfo_2eproto();
  friend void protobuf_ShutdownFile_youme_5fuserinfo_2eproto();

  void InitAsDefaultInstance();
  static UpdateUserInfoReq* default_instance_;
};
// -------------------------------------------------------------------

class UpdateUserInfoRsp : public ::youmecommon::protobuf::MessageLite {
 public:
  UpdateUserInfoRsp();
  virtual ~UpdateUserInfoRsp();

  UpdateUserInfoRsp(const UpdateUserInfoRsp& from);

  inline UpdateUserInfoRsp& operator=(const UpdateUserInfoRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const UpdateUserInfoRsp& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const UpdateUserInfoRsp* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(UpdateUserInfoRsp* other);

  // implements Message ----------------------------------------------

  inline UpdateUserInfoRsp* New() const { return New(NULL); }

  UpdateUserInfoRsp* New(::youmecommon::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::youmecommon::protobuf::MessageLite& from);
  void CopyFrom(const UpdateUserInfoRsp& from);
  void MergeFrom(const UpdateUserInfoRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::youmecommon::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::youmecommon::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateUserInfoRsp* other);
  private:
  inline ::youmecommon::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::youmecommon::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::youmecommon::protobuf::int32 version() const;
  void set_version(::youmecommon::protobuf::int32 value);

  // required int32 ret = 2;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 2;
  ::youmecommon::protobuf::int32 ret() const;
  void set_ret(::youmecommon::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.UpdateUserInfoRsp)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_ret();
  inline void clear_has_ret();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::youmecommon::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::youmecommon::protobuf::Arena* _arena_ptr_;

  ::youmecommon::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::youmecommon::protobuf::int32 version_;
  ::youmecommon::protobuf::int32 ret_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_youme_5fuserinfo_2eproto();
  #endif
  friend void protobuf_AssignDesc_youme_5fuserinfo_2eproto();
  friend void protobuf_ShutdownFile_youme_5fuserinfo_2eproto();

  void InitAsDefaultInstance();
  static UpdateUserInfoRsp* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GetUserInfoReq

// required int32 version = 1;
inline bool GetUserInfoReq::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetUserInfoReq::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetUserInfoReq::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetUserInfoReq::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::youmecommon::protobuf::int32 GetUserInfoReq::version() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.GetUserInfoReq.version)
  return version_;
}
inline void GetUserInfoReq::set_version(::youmecommon::protobuf::int32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.GetUserInfoReq.version)
}

// required bytes user_id = 2;
inline bool GetUserInfoReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetUserInfoReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetUserInfoReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetUserInfoReq::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_id();
}
inline const ::std::string& GetUserInfoReq::user_id() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.GetUserInfoReq.user_id)
  return user_id_.GetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetUserInfoReq::set_user_id(const ::std::string& value) {
  set_has_user_id();
  user_id_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.GetUserInfoReq.user_id)
}
inline void GetUserInfoReq::set_user_id(const char* value) {
  set_has_user_id();
  user_id_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YOUMEServiceProtocol.GetUserInfoReq.user_id)
}
inline void GetUserInfoReq::set_user_id(const void* value, size_t size) {
  set_has_user_id();
  user_id_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YOUMEServiceProtocol.GetUserInfoReq.user_id)
}
inline ::std::string* GetUserInfoReq::mutable_user_id() {
  set_has_user_id();
  // @@protoc_insertion_point(field_mutable:YOUMEServiceProtocol.GetUserInfoReq.user_id)
  return user_id_.MutableNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetUserInfoReq::release_user_id() {
  clear_has_user_id();
  return user_id_.ReleaseNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetUserInfoReq::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    set_has_user_id();
  } else {
    clear_has_user_id();
  }
  user_id_.SetAllocatedNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:YOUMEServiceProtocol.GetUserInfoReq.user_id)
}

// -------------------------------------------------------------------

// GetUserInfoRsp

// required int32 version = 1;
inline bool GetUserInfoRsp::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetUserInfoRsp::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetUserInfoRsp::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetUserInfoRsp::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::youmecommon::protobuf::int32 GetUserInfoRsp::version() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.GetUserInfoRsp.version)
  return version_;
}
inline void GetUserInfoRsp::set_version(::youmecommon::protobuf::int32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.GetUserInfoRsp.version)
}

// required bytes user_info = 2;
inline bool GetUserInfoRsp::has_user_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetUserInfoRsp::set_has_user_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetUserInfoRsp::clear_has_user_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetUserInfoRsp::clear_user_info() {
  user_info_.ClearToEmptyNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_info();
}
inline const ::std::string& GetUserInfoRsp::user_info() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.GetUserInfoRsp.user_info)
  return user_info_.GetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetUserInfoRsp::set_user_info(const ::std::string& value) {
  set_has_user_info();
  user_info_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.GetUserInfoRsp.user_info)
}
inline void GetUserInfoRsp::set_user_info(const char* value) {
  set_has_user_info();
  user_info_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YOUMEServiceProtocol.GetUserInfoRsp.user_info)
}
inline void GetUserInfoRsp::set_user_info(const void* value, size_t size) {
  set_has_user_info();
  user_info_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YOUMEServiceProtocol.GetUserInfoRsp.user_info)
}
inline ::std::string* GetUserInfoRsp::mutable_user_info() {
  set_has_user_info();
  // @@protoc_insertion_point(field_mutable:YOUMEServiceProtocol.GetUserInfoRsp.user_info)
  return user_info_.MutableNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetUserInfoRsp::release_user_info() {
  clear_has_user_info();
  return user_info_.ReleaseNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetUserInfoRsp::set_allocated_user_info(::std::string* user_info) {
  if (user_info != NULL) {
    set_has_user_info();
  } else {
    clear_has_user_info();
  }
  user_info_.SetAllocatedNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), user_info);
  // @@protoc_insertion_point(field_set_allocated:YOUMEServiceProtocol.GetUserInfoRsp.user_info)
}

// optional double longitude = 3;
inline bool GetUserInfoRsp::has_longitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetUserInfoRsp::set_has_longitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetUserInfoRsp::clear_has_longitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetUserInfoRsp::clear_longitude() {
  longitude_ = 0;
  clear_has_longitude();
}
inline double GetUserInfoRsp::longitude() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.GetUserInfoRsp.longitude)
  return longitude_;
}
inline void GetUserInfoRsp::set_longitude(double value) {
  set_has_longitude();
  longitude_ = value;
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.GetUserInfoRsp.longitude)
}

// optional double latitude = 4;
inline bool GetUserInfoRsp::has_latitude() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GetUserInfoRsp::set_has_latitude() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GetUserInfoRsp::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GetUserInfoRsp::clear_latitude() {
  latitude_ = 0;
  clear_has_latitude();
}
inline double GetUserInfoRsp::latitude() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.GetUserInfoRsp.latitude)
  return latitude_;
}
inline void GetUserInfoRsp::set_latitude(double value) {
  set_has_latitude();
  latitude_ = value;
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.GetUserInfoRsp.latitude)
}

// -------------------------------------------------------------------

// UpdateUserInfoReq

// required int32 version = 1;
inline bool UpdateUserInfoReq::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateUserInfoReq::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateUserInfoReq::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateUserInfoReq::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::youmecommon::protobuf::int32 UpdateUserInfoReq::version() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.UpdateUserInfoReq.version)
  return version_;
}
inline void UpdateUserInfoReq::set_version(::youmecommon::protobuf::int32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.UpdateUserInfoReq.version)
}

// required bytes user_info = 2;
inline bool UpdateUserInfoReq::has_user_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpdateUserInfoReq::set_has_user_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpdateUserInfoReq::clear_has_user_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpdateUserInfoReq::clear_user_info() {
  user_info_.ClearToEmptyNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_info();
}
inline const ::std::string& UpdateUserInfoReq::user_info() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.UpdateUserInfoReq.user_info)
  return user_info_.GetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateUserInfoReq::set_user_info(const ::std::string& value) {
  set_has_user_info();
  user_info_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.UpdateUserInfoReq.user_info)
}
inline void UpdateUserInfoReq::set_user_info(const char* value) {
  set_has_user_info();
  user_info_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YOUMEServiceProtocol.UpdateUserInfoReq.user_info)
}
inline void UpdateUserInfoReq::set_user_info(const void* value, size_t size) {
  set_has_user_info();
  user_info_.SetNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YOUMEServiceProtocol.UpdateUserInfoReq.user_info)
}
inline ::std::string* UpdateUserInfoReq::mutable_user_info() {
  set_has_user_info();
  // @@protoc_insertion_point(field_mutable:YOUMEServiceProtocol.UpdateUserInfoReq.user_info)
  return user_info_.MutableNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UpdateUserInfoReq::release_user_info() {
  clear_has_user_info();
  return user_info_.ReleaseNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateUserInfoReq::set_allocated_user_info(::std::string* user_info) {
  if (user_info != NULL) {
    set_has_user_info();
  } else {
    clear_has_user_info();
  }
  user_info_.SetAllocatedNoArena(&::youmecommon::protobuf::internal::GetEmptyStringAlreadyInited(), user_info);
  // @@protoc_insertion_point(field_set_allocated:YOUMEServiceProtocol.UpdateUserInfoReq.user_info)
}

// -------------------------------------------------------------------

// UpdateUserInfoRsp

// required int32 version = 1;
inline bool UpdateUserInfoRsp::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateUserInfoRsp::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateUserInfoRsp::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateUserInfoRsp::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::youmecommon::protobuf::int32 UpdateUserInfoRsp::version() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.UpdateUserInfoRsp.version)
  return version_;
}
inline void UpdateUserInfoRsp::set_version(::youmecommon::protobuf::int32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.UpdateUserInfoRsp.version)
}

// required int32 ret = 2;
inline bool UpdateUserInfoRsp::has_ret() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpdateUserInfoRsp::set_has_ret() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpdateUserInfoRsp::clear_has_ret() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpdateUserInfoRsp::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::youmecommon::protobuf::int32 UpdateUserInfoRsp::ret() const {
  // @@protoc_insertion_point(field_get:YOUMEServiceProtocol.UpdateUserInfoRsp.ret)
  return ret_;
}
inline void UpdateUserInfoRsp::set_ret(::youmecommon::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:YOUMEServiceProtocol.UpdateUserInfoRsp.ret)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace YOUMEServiceProtocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_youme_5fuserinfo_2eproto__INCLUDED
